export const managerEndpoint = "/manager";
export const roomEndpoint = "/room";
export const joinRoomEndpoint = (code: string) => `${roomEndpoint}/${code}/join`;
export const loginEndpoint = `${managerEndpoint}/login`;
export const roomInfoEndpoint = (code: string) => `${roomEndpoint}/${code}/info`;
export const roomQueueEndpoint = (code: string) => `${roomEndpoint}/${code}/queue`;
export const roomTopicQueueEndpoint = (code: string) => `/topic/queue${roomEndpoint}/${code}`;
export const queueRoomQueueEndpoint = (code: string) => `/queue${roomEndpoint}/${code}/queue`;
export const queueRoomEndpoint = (code: string) => `/queue${roomEndpoint}/${code}`;
export const roomManagerEndpoint = `${roomEndpoint}${managerEndpoint}`;
export const roomUsersEndpoint = (code: string) => `${roomEndpoint}/${code}/user/all`;
export const queueRoomPassEndpoint = (code: string) => `/queue${roomEndpoint}/${code}/pass`;
export const queueRoomSongEndpoint = (code: string, id: string) => `/queue${roomEndpoint}/${code}/${id}`;
export const usersTopicQueueEndpoint = (code: string) => `/topic/users${roomEndpoint}/${code}`;
export const roomTopicQueueUrlEndpoint = (code: string) => `/topic/queue${roomEndpoint}/${code}/url`;
export const managerUpgradePlanEndpoint = (type: string) => `${managerEndpoint}/upgrade/{id}/${type}`;
