export const defaultLanguage: string = "pt-br"
export const language: string = defaultLanguage;
export const url = import.meta.env.VITE_FRONT_URL;
export const backUrl = import.meta.env.VITE_BACK_URL; 
export const TIMEOUT = 10000;
export const youtubeUrl = import.meta.env.VITE_YOUTUBE_URL; 
export const youtubeKey = import.meta.env.VITE_YOUTUBE_KEY; 
export const lastfmUrl = import.meta.env.VITE_LASTFM_URL; 
export const lastfmKey = import.meta.env.VITE_LASTFM_KEY; 
